---
grails:
    profile: web
    codegen:
        defaultPackage: transmart.server
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    plugin:
        springsecurity:
            oauth2:
                active: true
                loginFormUrl: '/'
                providers:
                     google:
                        api_key: '223124584843-732fitr43ajd9aksqje0s9o4r8qtsugi.apps.googleusercontent.com'               #needed
                        api_secret: '2Dmw1Un9w8pXpILfBFIz30-V'         #needed
                        successUri: "/oauth2/google/success"    #optional
                        failureUri: "/oauth2/google/failure"    #optional
                        callback: "/oauth2/google/callback"     #optional
                        #scopes: "userinfo.email"                    #optional, see https://developers.google.com/identity/protocols/googlescopes#monitoringv3
#            successHandler:
#                alwaysUseDefault: true
#                defaultTargetUrl: '/'
#            failureHandler:
#                defaultFailureUrl: '/'
#                ajaxAuthFailUrl: '/'
                oauthProvider:
                      clientLookup:
                          className: 'org.transmart.org.transmart.oauth2.Client'
                      authorizationCodeLookup:
                          className: 'org.transmart.org.transmart.oauth2.AuthorizationCode'
                      accessTokenLookup:
                          className: 'org.transmart.org.transmart.oauth2.AccessToken'
                      refreshTokenLookup:
                          className: 'org.transmart.org.transmart.oauth2.RefreshToken'
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSources:
    dataSource:
        url: jdbc:postgresql://localhost:5432/transmart
        driverClassName: org.postgresql.Driver
        dialect: org.hibernate.dialect.PostgreSQLDialect
        username: tm_cz
        password: tm_cz
        dbCreate: none
    oauth2:
        driverClassName: 'org.h2.Driver'
        url: "jdbc:h2:~/.grails/oauth2db;MVCC=TRUE"
        dialect: 'org.hibernate.dialect.H2Dialect'
        username: 'sa'
        password: ''
        dbCreate: 'update'
        logSql: true
        formatSql: true

environments:
    development:
        dataSource:
            url: jdbc:postgresql://localhost:5432/transmart
            driverClassName: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQLDialect
            username: tm_cz
            password: tm_cz
            dbCreate: none
    test:
        dataSource:
            dbCreate: none
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: none
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
---
org:
  transmartproject:
    app:
      oauthEnabled: true

